// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Smart_Comment
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidSmart_CommentPackageString = "cf31a015-b474-422c-aae2-3dd1d534bccc";
        public static Guid guidSmart_CommentPackage = new Guid(guidSmart_CommentPackageString);

        public const string guidSmart_CommentPackageCmdSetString = "5c41565b-5ed3-40e1-b738-e8f46a17d54f";
        public static Guid guidSmart_CommentPackageCmdSet = new Guid(guidSmart_CommentPackageCmdSetString);

        public const string guidImagesString = "eeefe992-b4e3-4c8e-a87c-e9bb5b6d72fd";
        public static Guid guidImages = new Guid(guidImagesString);

        public const string guidImages1String = "723f2f10-f433-4ca6-89e9-5d8dc550d9d2";
        public static Guid guidImages1 = new Guid(guidImages1String);

        public const string guidImages2String = "3af3e02c-98b2-4f49-941f-c3360493404f";
        public static Guid guidImages2 = new Guid(guidImages2String);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int cmdidSCCommand = 0x0100;
        public const int cmdidSCSettingsWindowCommand = 0x1021;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}